# Generated by Django 4.2.5 on 2023-09-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='код приглашения'),
        ),
    ]
