# Generated by Django 4.2.5 on 2023-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invitation_code',
        ),
        migrations.AddField(
            model_name='user',
            name='my_invitation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='мой код приглашения'),
        ),
        migrations.AddField(
            model_name='user',
            name='someone_invite_code',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='чей-то код приглашения'),
        ),
    ]
