version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/tb4
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - redis

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py csu && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - /staticfiles/
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker --loglevel=info
    depends_on:
      - app
      - redis

volumes:
  pg_data: